version: '2.1'

services:
  database:
    container_name: "database"
    hostname: database
    restart: always
    extends:
      file: base.yml
      service: base
    build:
      context: .
      dockerfile: database-dockerfile
    volumes:
      - /vagrant/server-data/mysqldata:/var/lib/mysql:z
      - /vagrant/mysqlinit:/docker-entrypoint-initdb.d
    ports:
      - 12345:3306
    healthcheck:
      test: "exit 0"
      
  databasebackup:
    image: deitch/mysql-backup
    container_name: "databasebackup"
    hostname: databasebackup
    depends_on:
      database:
        condition: service_healthy
    restart: always
    user: "1000"
    extends:
      file: base.yml
      service: base
    volumes:
      - /vagrant/server-data/mysql-backup:/backup
    environment:
      DB_DUMP_TARGET: /backup
      DB_SERVER: database
      DB_PORT: 3306
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    extends:
      file: base.yml
      service: base
    ports:
      - 8181:80
    volumes:
      - /sessions
      - /vagrant/phpmyadminconf/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    links:
      - database:db    
     
  wlfly:
    container_name: "wlfly-app"
    hostname: wlfly-app
    restart: always
    extends:
      file: base.yml
      service: base
    build:
      context: .
      dockerfile: wildfly-dockerfile
    environment:
      JAVA_OPTS: "-Xms256m -Xmx768m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true"
    volumes:
      - /vagrant/server-data/wildfly-logs:/opt/jboss/wildfly/standalone/log
      - /vagrant/server-data/wildfly-deployments:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
      - 43974:43974
    links:
      - database:db
